version: '3.1'

services:

  db:
    image: postgres:13.2
    container_name: local_postgres_server
    volumes:
      - local_postgres_server_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypassword

volumes:
  local_postgres_server_volume:
